name: First action

on:
  workflow_dispatch:
  push:
    tags: 
      - 'v*.*.*'
      - '!v*.*.*-rc*'

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First action successfully finished!"
